feeds/urls.py
from django.conf.urls import include, patterns, url


view_location = 'feeds.views'

# used in feed system for redirect when appending zipcode onto url
homeCategory = 'shows'
homeScope = 'global'

urlpatterns = patterns(view_location,
    url(r'^follow/$',
        'follow', name='follow'),
    url(r'^remove_post/$',
        'remove_post', name='remove_post'),
    url(r'^upvote/$',
        'up_vote', name='upvote'),
    url(r'^zipcode/$',
        'zipcode', name='zipcode'),
    url(r'^filter/$',
        'filter', name='filter'),
    url(r'^genre/$',
        'genre', name='genre'),
    url(r'^availability/$',
        'availability', name='availability'),

    url(r'^(?P<order>[-\w]+)/', include(patterns(view_location,
        url(r'^artists/(?P<scope>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'^artists/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'artist/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_artists',
                name='available_artists'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_artists',
                name='available_artists'),
        ))),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^shows/(?P<scope>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^shows/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^venues/(?P<scope>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'^venues/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'venue/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_venues',
                name='available_venues'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_venues',
                name='available_venues'),
        ))),
    ))),
    url(r'^updates/', include(patterns(view_location,
        url(r'^(?P<scope>[-\w]+)/$',
            'updates',
            name='updates'),
        url(r'^(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'updates',
            name='updates'),
    ))),
)

messages/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic.base import RedirectView


urlpatterns = patterns('messages.views',
    url(r'^$', RedirectView.as_view(url='inbox/')),
    url(r'^inbox/$', 'inbox', name='messages_inbox'),
    url(r'^sent/$', 'sent', name='messages_sent'),
    url(r'^compose/$', 'compose', name='messages_compose'),
    url(r'^compose/(?P<recipient>[\+\w]+)/$', 'compose', name='messages_compose'),
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='messages_detail'),
    url(r'^delete/(?P<thread_id>[\d]+)/$', 'delete', name='messages_delete'),
    url(r'^restore/(?P<thread_id>[\d]+)/$', 'restore', name='messages_restore'),
    url(r'^batch-update/$', 'batch_update', name='messages_batch_update'),
    url(r'^trash/$', 'trash', name='messages_trash'),

    url(r'^message-reply/(?P<thread_id>[\d]+)/$', 'message_ajax_reply', name="message_reply"),

)

request/urls.py
from django.conf.urls import include, patterns, url


urlpatterns = patterns('request.views',
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='request_detail'),
    url(r'^application/view/(?P<thread_id>[\d]+)/$', 'application_view', name='application_view'),
    # Forms
    url(r'^$', 'requestForm', name='request_write'),
    url(r'^public/$', 'public_request_form', name='public_request'),
    url(r'^public/band/$', 'public_band_request_form', name='public_band_request'),
    url(r'^accept/$', 'accept', name='request_accept'),
    url(r'^decline/$', 'decline', name='request_decline'),
    url(r'^approve/$', 'approve', name='approve_public_request'),
    url(r'^deny/$', 'deny', name='deny_public_request'),
    url(r'^apply-to-band/(?P<request_id>[-\w]+)/$', 'appy_to_band', name='request_appy_to_band'),
    url(r'^apply-to-venue/(?P<request_id>[-\w]+)/$', 'appy_to_venue', name='request_appy_to_venue'),
    url(r'^create/(?P<username>[-\w]+)/$', 'requestForm', name='request_write'),
    url(r'^edit/(?P<request_id>[-\w]+)/$', 'requestEditForm', name='request_edit'),
)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'accounts/password_reset_form.html',
                    'email_template_name': 'accounts/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'accounts/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'accounts/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'accounts/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    #url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
    #   userena_views.direct_to_user_template,
    #   {'template_name': 'userena/signup_complete.html',
    #    'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
    #                      'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
    #   name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

request/models.py
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.utils.translation import ugettext as _

from accounts.models import MusicianProfile
from annoying.functions import get_object_or_None
from contact.models import Zipcode
from messages.models import Thread
from schedule.models.events import DateRange


class Request(models.Model):
    accept_by = models.DateField(_("accept_by"))
    date = models.ForeignKey(DateRange, verbose_name=_("dateRange"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class PrivateRequest(Request):
    messages = models.OneToOneField(Thread, verbose_name=_("messages"),
                                   related_name='request',
                                   null=True, blank=True)
    headliner = models.ForeignKey(MusicianProfile,
                                  verbose_name=_("headliner"),
                                  related_name='request_for_headlining')
    openers = models.ManyToManyField(MusicianProfile,
                                     verbose_name=_("openers"),
                                     related_name='request_for_opening',
                                     null=True, blank=True)
    host = models.ForeignKey(User, verbose_name=_("host"))

    def participants(self):
        participants = []
        if self.host:
            participants.append(self.host)
        if self.headliner:
            participants.append(self.headliner.profile.user)
        for opener in self.openers.all():
            participants.append(opener.profile.user)
        return participants

    def has_accepted(self, user):
        a = get_object_or_None(Accept, user=user, request=self)
        if a:
            return a.accepted
        else:
            return None

class Accept(models.Model):
    user = models.ForeignKey(User, related_name='accepter')
    request = models.ForeignKey(PrivateRequest, related_name='accepted_request')
    accepted = models.BooleanField()

class PublicRequest(Request):
    zip_code = models.ForeignKey(Zipcode, verbose_name=_("Zipcode"))
    details = models.TextField(_("description"))
    requester = models.ForeignKey(User, verbose_name=_("requester"))
    fulfilled = models.BooleanField(_('fulfilled'), default=False)
    objects = models.GeoManager()

    def save(self, requester=None, date=None, *args, **kwargs):
        if requester:
            self.requester = requester
        if date:
            self.date = date
        super(PublicRequest, self).save(*args, **kwargs)

class NumberOfApplicants(models.Model):
    public_request = models.OneToOneField(PublicRequest,
                                          verbose_name=_("public_request"),
                                          related_name='applicants',)
    left = models.PositiveSmallIntegerField(verbose_name=_("total_bands"))
    total = models.PositiveSmallIntegerField(verbose_name=_("number_of_bands"))
    def save(self, public_request=None, *args, **kwargs):
        if public_request:
            self.public_request = public_request
        if not self.left:
            self.left = self.total
        super(NumberOfApplicants, self).save(*args, **kwargs)

class Application(models.Model):
    public_request = models.ForeignKey(PublicRequest,
                                       verbose_name=_("public_request"),
                                       related_name='applications',)
    thread = models.OneToOneField(Thread, verbose_name=_("thread"),
                                   related_name='application',
                                   null=True, blank=True)
    applicant = models.ForeignKey(User, verbose_name=_("requester"))
    approved = models.NullBooleanField(_('approved'), default=None)

composersCouch/views.py
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic import FormView
from django.views.generic.base import TemplateView

from accounts.models import FanProfile, MusicianProfile, VenueProfile
from feeds.views import requests, shows


def load_template(request, template_name, extra_context=None):
    if not extra_context: extra_context = dict()
    return render(request, template_name, extra_context)

def search(request, template_name='search/search.html', ajax_template='autocomplete/search.html'):
    if request.is_ajax():
        template_name = ajax_template

    q = request.GET.get('q', '')
    context = {'q': q}
    queries = {}
    queries['musicians'] = MusicianProfile.objects.filter(name__icontains=q)[:3]
    queries['venues'] = VenueProfile.objects.filter(name__icontains=q)[:3]

    context.update(queries)
    return render(request, template_name, context)

class HomeView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            if self.request.user.profile.profile_type == 'm':
                return requests(self.request, scope='local', kwargs={'for':'band','scope':'local'})
            elif self.request.user.profile.profile_type == 'v':
                return requests(self.request, scope='local', kwargs={'for':'venue','scope':'local'})
            else:
                return shows(self.request, scope='local')
        return super(HomeView, self).dispatch(*args, **kwargs)

home = HomeView.as_view()

# Mixin to handle multiple form classses
class MultipleFormsView(FormView):
    form_classes = {}
    template_name = None
    success_url = 'home'

    def are_forms_valid(self, forms):
        for key, form in forms.iteritems():
            if not form.is_valid():
                return False
        return True

    def forms_valid(self, forms):
        return get_success_url(self, **kwargs)

    def forms_invalid(self, forms):
        context = self.get_context_data()
        context['next'] = self.request.POST.get('next')
        context.update(forms)
        return render(self.request, self.template_name, context)

    def get(self, request, username=None, **kwargs):
        context = self.get_context_data()
        context.update(self.get_forms())
        # TODO: append next url to response?
        return render_to_response(self.template_name,
                                  context_instance=RequestContext(request, context))

    def get_context_data(self, **kwargs):
        context = super(MultipleFormsView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context

    def get_forms(self):
        forms = {}
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(initial=initial[key], **form_kwargs)
        return forms

    def get_form_kwargs(self):
        kwargs = {}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_initial_data(self):
        initial = {}
        for key, form_class in self.form_classes.iteritems():
            initial[key] = {}
        return initial

    def get_success_url(self, **kwargs):
        if self.request.POST.has_key('next'):
            return HttpResponseRedirect(self.request.POST['next'])
        else:
            return redirect(self.success_url, **kwargs)

    def post(self, request, **kwargs):
        forms = self.get_forms()
        if self.are_forms_valid(forms):
            return self.forms_valid(forms)
        else:
            return self.forms_invalid(forms)

class MultipleModelFormsView(MultipleFormsView):
    """ The object coresponding to the form must use the sam key """

    def get_objects(self):
        objects = {}
        for key, form_class in self.form_classes.iteritems():
            objects[key] = None
        return objects

    def get_forms(self):
        forms = {}
        objects = self.get_objects()
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(instance=objects[key], initial=initial[key], **form_kwargs)
        return forms


def reset():
     cursor = connection.cursor()
     cursor.execute("SELECT setval('location_id_key', (SELECT MAX(id) FROM contact_location)+1)")
     print "success"

composersCouch/templates/request/_accepted.html
{% if accepted %}
  <span class="text-success" ><span class="fa fa-check"></span>Accepted</span>
{% elif accepted != None %}
  <span class="text-danger" ><span class="fa fa-ban"></span> Declined</span>
{% endif %}

composersCouch/templates/request/_public_request.html
{% load i18n %}

<div class="request">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-2 col-sm-3">
          <div class="image-frame">
            <span class="frame-helper"></span>
            {% include "utils/_mugshot.html" with profile=publicRequest.requester.profile width=100 height=100 %}
          </div>
        </div>
        <div class="col-lg-8 col-sm-7">
          <a class="text-black" href="{% url 'redirectToProfile' publicRequest.requester.username 'about' %}">
            <h3>{{ publicRequest.requester.profile }}</h3>
          </a>
          <div>Accept By: {{ publicRequest.accept_by }}</div>
          <div>At: {{ publicRequest.zip_code }}</div>
          {% if publicRequest.applicants %}
          <div>Looking for {{ publicRequest.applicants.left }} bands</div>
          {% endif %}
          <p>{{ publicRequest.details }}</p>
        </div>
        <div class="col-sm-2">
          <div class="date-block">
            {% include "utils/dates/_start_end_visual.html" with start=publicRequest.date.start end=publicRequest.date.end %}
          </div>
        </div>
      </div>
    </div>
    {% if user.is_authenticated and not noApply and not publicRequest.fulfilled %}
      {% if publicRequest.applicants and user.profile.profile_type == 'm' %}
        <div class="panel-footer text-right">
          <a href="{% url 'request_appy_to_venue' publicRequest.id %}" class="btn btn-default">Apply</a>
        </div>
      {% elif not publicRequest.applicants %}
        <div class="panel-footer text-right">
          <a href="{% url 'request_appy_to_band' publicRequest.id %}" class="btn btn-default">Apply</a>
        </div>
      {% endif %}
    {% endif %}
  </div>
</div>

composersCouch/templates/request/application_view.html
{% extends "messages/view.html" %}
{% load i18n %}

{% block from %}{% endblock %}

{% block card %}
  <h3>Request</h3>
  {% include "request/_public_request.html" with publicRequest=public_request noApply=True %}
  <h3>Applicant</h3>
  {% with applicant=application.applicant %}
    <div class="applicant">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-2 col-sm-3">
              <div class="image-frame">
                <span class="frame-helper"></span>
                {% include "utils/_mugshot.html" with profile=applicant.profile width=75 height=75 %}
              </div>
            </div>
            <div class="col-lg-8 col-sm-7">
              <a class="text-black" href="{% url 'venue:about' application.applicant.username  %}">
                <h3>{{ applicant.profile }}</h3>
              </a>
              {% if applicant.biography %}
                <p>{{ applicant.biography }}</p>
              {% endif %}
            </div>
          </div>
        </div>
        {% if user == public_request.requester %}
        <div class="panel-footer">
          <div class="text-right">
            <form method="POST" class="accept-form inline-block {% if application.approved %}hidden{% endif %}" action="{% url 'approve_public_request' %}">
              {% csrf_token %}
              <input type="hidden" name="application" value="{{ application.id }}">
              <button class="btn btn-success" type="submit"><span class="fa fa-check" ></span> {% trans "Accept" %}</button>
            </form>
            <form method="POST" class="decline-form inline-block {% if application.approved %}{% elif application.approved != None %}hidden{% endif %}" action="{% url 'deny_public_request' %}">
              {% csrf_token %}
              <input type="hidden" name="application" value="{{ application.id }}">
              <button class="btn btn-danger" type="submit"><span class="fa fa-ban" ></span> {% trans "Decline" %}</button>
            </form>
          </div>
          {% comment %}
          <a href="{% url 'calendar_request_to_event' user.calendar.slug request.id %}" class="btn btn-link">{% trans "Add to Calendar" %}</a>
          {% endcomment %}
        </div>
        {% endif %}
      </div>
    </div>
    {% if publicRequest.applicants %}
    {% endif %}
  {% endwith %}

{% endblock %}

composersCouch/templates/request/apply_form.html
{% extends 'form.html' %}
{% load i18n crispy_forms_tags %}
{% crispy MessageForm MessageForm.helper %}

{% block title %}{% block formTitle %}
  {% trans "Apply to Request" %}
{% endblock %}{% endblock %}

{% block formID %}applyForm{% endblock %}

{% block form %}
  {% include "request/_public_request.html" with publicRequest=public_request noApply=True %}
  {% crispy form %}
{% endblock %}

{% block submit %}<button type="submit" class="btn btn-primary">{% trans 'Send' %}</button>{% endblock %}

composersCouch/templates/request/edit_request_form.html
{% extends 'form.html' %}
{% load i18n crispy_forms_tags %}
{% crispy DateForm DateForm.helper %}
{% crispy PrivateRequestForm PrivateRequestForm.helper %}

{% block title %}{% block formTitle %}
  {% trans "Edit Request" %}
{% endblock %}{% endblock %}

{% block formID %}privateRequestEditForm{% endblock %}

{% block form %}
  {% crispy dateForm %}
  {% crispy requestForm %}
{% endblock %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript">
    $(function () {
      $('#id_start_0').datetimepicker({pickTime: false});
      $('#id_start_1').datetimepicker({pickDate: false});
      $('#id_end_0').datetimepicker({pickTime: false});
      $('#id_end_1').datetimepicker({pickDate: false});
      $('#id_accept_by').datetimepicker({pickTime: false});
    });
  </script>
{% endblock %}

composersCouch/templates/request/privaterequest_form.html
{% extends 'form.html' %}
{% load i18n crispy_forms_tags %}
{% crispy DateForm DateForm.helper %}
{% crispy MessageForm MessageForm.helper %}
{% crispy PrivateRequestForm PrivateRequestForm.helper %}

{% block title %}{% block formTitle %}
  {% trans "Send Request" %}
{% endblock %}{% endblock %}

{% block formID %}privateRequestForm{% endblock %}

{% block form %}
  {% crispy dateForm %}
  {% crispy requestForm %}
  {% crispy messageForm %}
{% endblock %}

{% block submit %}<button type="submit" class="btn btn-primary">{% trans 'Send' %}</button>{% endblock %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript">
    $(function () {
        $('#id_start_0').datetimepicker({pickTime: false});
        $('#id_start_1').datetimepicker({pickDate: false});
        $('#id_end_0').datetimepicker({pickTime: false});
        $('#id_end_1').datetimepicker({pickDate: false});
        $('#id_accept_by').datetimepicker({pickTime: false});
    });
  </script>
{% endblock %}

composersCouch/templates/request/publicrequest_form.html
{% extends 'form.html' %}
{% load i18n crispy_forms_tags %}
{% crispy DateForm DateForm.helper %}
{% crispy PublicRequestForm PublicRequestForm.helper %}
{% crispy NumberOfApplicantsForm NumberOfApplicantsForm.helper %}

{% block title %}{% block formTitle %}
  {% trans "Create Request" %}
{% endblock %}{% endblock %}

{% block formID %}publicRequestForm{% endblock %}

{% block form %}
    {% crispy dateForm %}
    {% if numApplicantsForm %}
      {% crispy numApplicantsForm %}
    {% endif %}
    {% crispy requestForm %}
{% endblock %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript">
    $(function () {
        $('#id_start_0').datetimepicker({pickTime: false});
        $('#id_start_1').datetimepicker({pickDate: false});
        $('#id_end_0').datetimepicker({pickTime: false});
        $('#id_end_1').datetimepicker({pickDate: false});
        $('#id_accept_by').datetimepicker({pickTime: false});
    });
  </script>
{% endblock %}

composersCouch/templates/request/view.html
{% extends "messages/view.html" %}
{% load thumbnail scheduletags i18n annoying %}

{% block from %}{% endblock %}
{% block card %}
  {% with request=thread.request %}
    <div class="request">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-6">
              <div class="Headliner">
                <b>Headliner:</b>
                <a class="text-black" href="{% url 'redirectToProfile' request.headliner.profile.user.username 'about' %}">
                  {{ request.headliner.name }}
                </a>
                {% include "request/_accepted.html" with accepted=headliner_accept %}
              </div>
              {% if request.openers.first %}
              <div class="Performers">
                <b>Performers:</b>
                {% for o in openers_accept %}
                <a class="text-black" href="{% url 'redirectToProfile' o.0.profile.user.username 'about' %}">
                  {{ o.0 }}
                </a>
                {% include "request/_accepted.html" with accepted=o.1 %}
                {% endfor %}
              </div>
              {% endif %}
              {% with host=request.host %}
              <div class="host">
                <b>Host:</b>
                <a class="text-black" href="{% url 'redirectToProfile' host.username 'about' %}">{{ host.profile }}</a>
                {% include "request/_accepted.html" with accepted=host_accept %}
              </div>
              {% endwith %}
              <p>Accept by: {{ request.accept_by }}</p>
            </div>
            <div class="col-sm-6">
              <h4>Suggested dates:</h4>
              <p>
                {% include "utils/dates/_start_end_full.html" with start=request.date.start end=request.date.end %}
              </p>
              <div>
                {% for event in events %}
                  {% ifchanged event.show.date.start.day %}
                    <p><b>{{ event.show.date.start|date:'N j' }}</b></p>
                  {% endifchanged %}
                    <p>
                      {{ event.show.date.start|date:'fA' }} - {{ event.show.info.title }} {{ event.show.info.headliner }}
                      {% if event.approved == None %}
                        <span class="label label-warning">pending</span>
                      {% endif %}
                    </p>
                  {% empty %}
                    <p>Your calendar is free</p>
                {% endfor %}
              </div>
              <a href="{% url 'request_edit' request.id %}" class="">{% trans "Edit" %}</a>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <div class="text-right">
            <form method="POST" class="accept-form inline-block {% if user_accept %}hidden{% endif %}" action="{% url 'request_accept' %}">
              {% csrf_token %}
              <input type="hidden" name="private_request" value="{{ request.id }}">
              <button class="btn btn-success" type="submit"><span class="fa fa-check" ></span> {% trans "Accept" %}</button>
            </form>
            <form method="POST" class="decline-form inline-block {% if user_accept %}{% elif user_accept != None %}hidden{% endif %}" action="{% url 'request_decline' %}">
              {% csrf_token %}
              <input type="hidden" name="private_request" value="{{ request.id }}">
              <button class="btn btn-danger" type="submit"><span class="fa fa-ban" ></span> {% trans "Decline" %}</button>
            </form>
          </div>
          <a href="{% url 'calendar_request_to_event' user.calendar.slug request.id %}" class="btn btn-link">{% trans "Add to Calendar" %}</a>
        </div>
      </div>
    </div>
  {% endwith %}
{% endblock %}