feeds/urls.py
from django.conf.urls import include, patterns, url


view_location = 'feeds.views'

# used in feed system for redirect when appending zipcode onto url
homeCategory = 'shows'
homeScope = 'global'

urlpatterns = patterns(view_location,
    url(r'^follow/$',
        'follow', name='follow'),
    url(r'^remove_post/$',
        'remove_post', name='remove_post'),
    url(r'^upvote/$',
        'up_vote', name='upvote'),
    url(r'^zipcode/$',
        'zipcode', name='zipcode'),
    url(r'^filter/$',
        'filter', name='filter'),
    url(r'^genre/$',
        'genre', name='genre'),
    url(r'^availability/$',
        'availability', name='availability'),

    url(r'^(?P<order>[-\w]+)/', include(patterns(view_location,
        url(r'^artists/(?P<scope>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'^artists/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'artist/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_artists',
                name='available_artists'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_artists',
                name='available_artists'),
        ))),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^shows/(?P<scope>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^shows/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^venues/(?P<scope>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'^venues/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'venue/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_venues',
                name='available_venues'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_venues',
                name='available_venues'),
        ))),
    ))),
    url(r'^updates/', include(patterns(view_location,
        url(r'^(?P<scope>[-\w]+)/$',
            'updates',
            name='updates'),
        url(r'^(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'updates',
            name='updates'),
    ))),
)

messages/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic.base import RedirectView


urlpatterns = patterns('messages.views',
    url(r'^$', RedirectView.as_view(url='inbox/')),
    url(r'^inbox/$', 'inbox', name='messages_inbox'),
    url(r'^sent/$', 'sent', name='messages_sent'),
    url(r'^compose/$', 'compose', name='messages_compose'),
    url(r'^compose/(?P<recipient>[\+\w]+)/$', 'compose', name='messages_compose'),
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='messages_detail'),
    url(r'^delete/(?P<thread_id>[\d]+)/$', 'delete', name='messages_delete'),
    url(r'^restore/(?P<thread_id>[\d]+)/$', 'restore', name='messages_restore'),
    url(r'^batch-update/$', 'batch_update', name='messages_batch_update'),
    url(r'^trash/$', 'trash', name='messages_trash'),

    url(r'^message-reply/(?P<thread_id>[\d]+)/$', 'message_ajax_reply', name="message_reply"),

)

schedule/urls.py
from django.conf.urls import include, patterns, url


view_location = 'schedule.views'
urlpatterns = patterns(view_location,
    url(r'^calendar/', include(patterns(view_location,
        url(r'^year/(?P<calendar_slug>[-\w]+)/$', 'year', name="year_calendar"),
        url(r'^month/(?P<calendar_slug>[-\w]+)/$', 'month', name="month_calendar"),
        url(r'^week/(?P<calendar_slug>[-\w]+)/$', 'week', name="week_calendar"),
        url(r'^day/(?P<calendar_slug>[-\w]+)/$', 'day', name="day_calendar"),
    ))),

    url(r'^show/', include(patterns(view_location,
        url(r'^create/(?P<calendar_slug>[-\w]+)/$', 'create_event', name='calendar_create_event'),
        url(r'^edit/(?P<calendar_slug>[-\w]+)/(?P<show_id>\d+)/$', 'edit_event', name='edit_event'),
        url(r'^requestToEvent/(?P<calendar_slug>[-\w]+)/(?P<request_id>\d+)/$', 'request_to_event', name='calendar_request_to_event'),
        url(r'^view/(?P<calendar_slug>[-\w]+)/(?P<show_id>\d+)/$', 'show', name="show"),
        url(r'^view-message/(?P<thread_id>\d+)/$', 'show_message', name="show_message"),
        url(r'^confirm/$', 'confirm', name='show_confirm'),
        url(r'^deny/$', 'deny', name='show_deny'),
    ))),
)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'accounts/password_reset_form.html',
                    'email_template_name': 'accounts/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'accounts/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'accounts/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'accounts/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    #url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
    #   userena_views.direct_to_user_template,
    #   {'template_name': 'userena/signup_complete.html',
    #    'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
    #                      'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
    #   name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

schedule/models/shows.py
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _

from accounts.models import MusicianProfile
from contact.models import Location
from photos.models import Image


AGE = (
    ('All', _('All')),
    ('18+', _('18+')),
    ('21+', _('21+')),
)
class Info(models.Model):
    '''
    This model stores meta data for a date.  You can relate this data to many
    other models.
    '''
    poster = models.ForeignKey(Image,
                              verbose_name=_("Poster"),
                              related_name='event poster',null=True,
                              blank=True)
    title = models.CharField(_("title"), max_length = 255, null=True, blank=True,)
    description = models.TextField(_("description"), null=True,
                                   blank=True)
    headliner = models.ForeignKey(MusicianProfile,
                                  null=True, blank=True,
                                  verbose_name=_("headliner"),
                                  related_name='shows_headlining')
    openers = models.ManyToManyField(MusicianProfile,
                                     null=True, blank=True,
                                     verbose_name=_("openers"),
                                     related_name='shows_opening')
    host = models.ForeignKey(User, verbose_name=_("host"))
    location = models.ForeignKey(Location,
                                null=True, blank=True,
                                verbose_name=_("location"),
                                related_name='event_location')
    age =  models.CharField(_('age'), max_length=3, choices=AGE,
                            default=AGE[0][0])
    advance_price = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=True, blank=True,
                                        verbose_name=_("advance_price"))
    full_price = models.DecimalField(max_digits=6, decimal_places=2,
                                     null=True, blank=True,
                                     verbose_name=_("full_price"))
    objects = models.GeoManager()

    def participants(self):
        participants = []
        if self.host:
            participants.append(self.host)
        if self.headliner:
            participants.append(self.headliner.profile.user)
        for opener in self.openers.all():
            participants.append(opener.profile.user)
        return participants

    def get_poster(self):
        if self.poster:
            return self.poster.image
        elif self.headliner:
            return self.headliner.profile.mugshot.image
        elif self.host:
            return self.host.profile.mugshot.image
        return None

    def get_title(self):
        if self.title:
            return self.title
        elif self.headliner:
            return self.headliner.profile
        return "Show"

    class Meta:
        verbose_name = _('info')
        app_label = 'schedule'

composersCouch/views.py
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic import FormView
from django.views.generic.base import TemplateView

from accounts.models import FanProfile, MusicianProfile, VenueProfile
from feeds.views import requests, shows


def load_template(request, template_name, extra_context=None):
    if not extra_context: extra_context = dict()
    return render(request, template_name, extra_context)

def search(request, template_name='search/search.html', ajax_template='autocomplete/search.html'):
    if request.is_ajax():
        template_name = ajax_template

    q = request.GET.get('q', '')
    context = {'q': q}
    queries = {}
    queries['musicians'] = MusicianProfile.objects.filter(name__icontains=q)[:3]
    queries['venues'] = VenueProfile.objects.filter(name__icontains=q)[:3]

    context.update(queries)
    return render(request, template_name, context)

class HomeView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            if self.request.user.profile.profile_type == 'm':
                return requests(self.request, scope='local', kwargs={'for':'band','scope':'local'})
            elif self.request.user.profile.profile_type == 'v':
                return requests(self.request, scope='local', kwargs={'for':'venue','scope':'local'})
            else:
                return shows(self.request, scope='local')
        return super(HomeView, self).dispatch(*args, **kwargs)

home = HomeView.as_view()

# Mixin to handle multiple form classses
class MultipleFormsView(FormView):
    form_classes = {}
    template_name = None
    success_url = 'home'

    def are_forms_valid(self, forms):
        for key, form in forms.iteritems():
            if not form.is_valid():
                return False
        return True

    def forms_valid(self, forms):
        return get_success_url(self, **kwargs)

    def forms_invalid(self, forms):
        context = self.get_context_data()
        context['next'] = self.request.POST.get('next')
        context.update(forms)
        return render(self.request, self.template_name, context)

    def get(self, request, username=None, **kwargs):
        context = self.get_context_data()
        context.update(self.get_forms())
        # TODO: append next url to response?
        return render_to_response(self.template_name,
                                  context_instance=RequestContext(request, context))

    def get_context_data(self, **kwargs):
        context = super(MultipleFormsView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context

    def get_forms(self):
        forms = {}
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(initial=initial[key], **form_kwargs)
        return forms

    def get_form_kwargs(self):
        kwargs = {}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_initial_data(self):
        initial = {}
        for key, form_class in self.form_classes.iteritems():
            initial[key] = {}
        return initial

    def get_success_url(self, **kwargs):
        if self.request.POST.has_key('next'):
            return HttpResponseRedirect(self.request.POST['next'])
        else:
            return redirect(self.success_url, **kwargs)

    def post(self, request, **kwargs):
        forms = self.get_forms()
        if self.are_forms_valid(forms):
            return self.forms_valid(forms)
        else:
            return self.forms_invalid(forms)

class MultipleModelFormsView(MultipleFormsView):
    """ The object coresponding to the form must use the sam key """

    def get_objects(self):
        objects = {}
        for key, form_class in self.form_classes.iteritems():
            objects[key] = None
        return objects

    def get_forms(self):
        forms = {}
        objects = self.get_objects()
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(instance=objects[key], initial=initial[key], **form_kwargs)
        return forms


def reset():
     cursor = connection.cursor()
     cursor.execute("SELECT setval('location_id_key', (SELECT MAX(id) FROM contact_location)+1)")
     print "success"

composersCouch/templates/schedule/_calendar_nav.html
{% load scheduletags i18n %}

<div class="col-xs-10 right">
  <div class="btn-toolbar hidden-xs" role="toolbar">
    <div class="btn-group pull-right">
      <a href="{% url 'day_calendar' calendar.slug %}{% querystring_for_date date 3 %}" class="btn btn-default {% if day %}active{% endif %}">
        {% trans "Day" %}
      </a>
      <a href="{% url 'week_calendar' calendar.slug %}{% querystring_for_date date 3 %}" class="btn btn-default {% if week %}active{% endif %}">
        {% trans "Week" %}
      </a>
      <a href="{% url 'month_calendar' calendar.slug %}{% querystring_for_date date 2 %}" class="btn btn-default {% if month %}active{% endif %}">
        {% trans "Month" %}
      </a>
      <a href="{% url 'year_calendar' calendar.slug %}{% querystring_for_date date 1 %}" class="btn btn-default {% if year %}active{% endif %}">
        {% trans "Year" %}
      </a>
    </div>
    <div class="btn-group pull-right">
      <a href="{% url 'month_calendar' calendar.slug %}" class="btn btn-default">
        {% trans "Today" %}
      </a>
    </div>
  </div>
  <div class="btn-toolbar visible-xs" role="toolbar">
    <div class="btn-group pull-right">
      <div class="btn-group pull-right">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          {% if day %}Day{% elif week %}Week{% elif month %}Month{% elif year %}Year{% endif %} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li class="{% if day %}active{% endif %}">
            <a href="{% url 'day_calendar' calendar.slug %}{% querystring_for_date date 3 %}">
              {% trans "Day" %}
            </a>
          </li>
          <li class="{% if week %}active{% endif %}">
            <a href="{% url 'week_calendar' calendar.slug %}{% querystring_for_date date 3 %}">
              {% trans "Week" %}
            </a>
          </li>
          <li class="{% if month %}active{% endif %}">
            <a href="{% url 'month_calendar' calendar.slug %}{% querystring_for_date date 2 %}" >
              {% trans "Month" %}
            </a>
          </li>
          <li class="{% if year %}active{% endif %}">
            <a href="{% url 'year_calendar' calendar.slug %}{% querystring_for_date date 1 %}">
              {% trans "Year" %}
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="btn-group pull-right">
      <a href="{% url 'month_calendar' calendar.slug %}" class="btn btn-default">
        {% trans "Today" %}
      </a>
    </div>
  </div>
</div>

composersCouch/templates/schedule/_create_event_options.html
{% load staticfiles i18n %}
<a href="{{ create_event_url }}&amp;next={{here}}" class="text-success"><span class="fa fa-plus"></span></a>

composersCouch/templates/schedule/_detail.html
{% load i18n %}
<div class="detail">
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
    <tr>
        <td class="left">{% trans "Starts" %}</td>
        <td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
    </tr>
    <tr>
        <td class="left">{% trans "Ends" %}</td>
        <td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
    </tr>
    {% if occurrence.event.rule %}
        {% if not occurrence.id %}
            <tr>
                <td class="left">{% trans "Reoccurs" %}</td><td>{{occurrence.event.rule}}</td>
            </tr>
            {% if occurrence.event.end_recurring_period %}
                <tr>
                    <td class="left">{% trans "Until" %}</td>
                    <td>{% blocktrans with occurrence.event.end_recurring_period|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
                </tr>
            {% endif %}
        {% endif %}
    {% endif %}
</table>
{% if occurrence.description %}
<h3>{% trans "Description" %}</h3>
<p>{{occurrence.description}}</p>
{% endif %}
</div>

composersCouch/templates/schedule/_dialogs.html
{% block extra_head %}
{% load i18n %}
<script>
function openCancelDialog(node, cancel_url, delete_url, event){
  event.stopPropagation();
  var btns = {"{% trans "This" %}":function(){window.location=cancel_url;}, "{% trans "All" %}":function(){window.location=delete_url}, "{% trans "Do nothing" %}":function(){$(this).dialog("destroy");}};
  dia = $("#delete_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openEditDialog(node, occurrence_url, event_url, event){
  event.stopPropagation();
  var btns = {"{% trans "This" %}":function(){window.location=occurrence_url;}, "{% trans "All" %}":function(){window.location=event_url}, "{% trans "Do nothing" %}":function(){$(this).dialog("destroy");}};
  dia = $("#edit_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openDetail(node){
  var btns = { "{% trans "Close" %}":function(){$(this).dialog("destroy");}};
  dia = $($(node).attr("href")).dialog({'buttons':btns, 'modal':true, 'title':'Details'});
  dia.dialog('open');
  return false;
}

function openURL(url, event){
    event.stopPropagation();
    window.location=url;
}
</script>
{% endblock %}


<div style="display:none;" id="delete_dialog" title="Question">
  {% trans "Do you want to cancel this occurrence or delete all occurrences of this event?" %}
</div>

<div style="display:none;" id="edit_dialog" title="This is a recurring event">
  {% trans "Do you want to edit this occurrence or all occurrences?" %}
</div>

composersCouch/templates/schedule/_event_options.html
{% load staticfiles i18n %}

<span class="actions">
{% if edit_event %}
<span class="edit">
{% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="javascript:void(0)" onclick="openURL('{{ edit_occurrence }}?next={{ here }}', event);">
            <span class="fa fa-pencil"></span>
        </a>
    {% else %}
        <a href="javascript:void(0)" onclick="openEditDialog(this, '{{ edit_occurrence }}?next={{ here }}', '{{ edit_event }}?next={{ here }}', event);">
            <span class="fa fa-pencil"></span>
        </a>
    {% endif %}
{% else %}
    <a href="javascript:void(0)" onclick="openURL('{{ edit_event }}?next={{ here }}', event);">
        <span class="fa fa-pencil"></span>
    </a>
{% endif %}
{% endif %}
</span>
{% if delete_event %}
<span class="delete">
{% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="javascript:void(0)" onclick="openURL('{{cancel_occurrence}}?next={{here}}', event);">
            <span class="fa fa-trash-o"></span>
        </a>
    {% else %}
        <a href="javascript:void(0)" onclick="openCancelDialog(this, '{{ cancel_occurrence }}?next={{here}}', '{{delete_event}}?next={{here}}', event);">
            <span class="fa fa-trash-o"></span>
        </a>
    {% endif %}
{% else %}
<a href="javascript:void(0)" onclick="openURL('{{delete_event}}?next={{here}}', event);">
  <span class="fa fa-trash-o"></span>
</a>
{% endif %}
{% endif %}
</span>
</span>

composersCouch/templates/schedule/_event_title.html
<span class="title">{{occurrence.title}}</span>

composersCouch/templates/schedule/_month_table.html
{% load scheduletags %}
<div class="calendar {{month}}">
  {% if weekday_abbrs or weekday_names %}
    <div class="cal-row-fluid cal-row-head">
      {% ifequal size "small" %}
        {% for day_name in weekday_names %}
          <div class="visible-sm cal-cell1">
            <h5>{{ day_name }}</h5>
          </div>
        {% endfor %}
        {% for day_name in weekday_abbrs %}
          <div class="hidden-sm cal-cell1">
            <h5>{{ day_name }}</h5>
          </div>
        {% endfor %}
      {% else %}
        {% for day_name in weekday_names %}
          <div class="hidden-xs cal-cell1">
            <h5>{{ day_name }}</h5>
          </div>
        {% endfor %}
        {% for day_name in weekday_abbrs %}
          <div class="visible-xs cal-cell1">
            <h5>{{ day_name }}</h5>
          </div>
        {% endfor %}
      {% endifequal %}
    </div>
  {% endif %}
  <div class="cal-month-box">
    {% for week in month.get_weeks %}
      <div class="week">
        <div class="cal-row-fluid row-eq-height cal-day-row">
          <div id="week-link">
            <a href="{% url 'week_calendar' calendar.slug %}{% querystring_for_date week.start %}">
              Week
            </a>
          </div>
          {% for day in week.get_days %}
            {% day_cell calendar day month size %}
          {% endfor %}
        </div>
        <div class="row expanded-day">
          <div class="col-xs-8"><ul class="event-list list-unstyled"></ul></div>
          <div class="col-xs-4 link-list"></div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

composersCouch/templates/schedule/create_event.html
{% extends "form.html" %}
{% load crispy_forms_tags i18n progress_bar %}
{% crispy DateForm DateForm.helper %}
{% crispy EventForm EventForm.helper %}
{% crispy ShowInfoForm ShowInfoForm.helper %}

{% block title %}
  {% block formTitle %}{% trans "Create Event" %}{% endblock %}
{% endblock %}

{% block formID %}eventForm{% endblock %}
{% block enctype %}multipart/form-data{% endblock %}
{% block form %}
  <div id="poster-form">
    {% crispy poster_form %}
    {% if images %}
      {% include "utils/_image_select.html" with images=images id="poster" label="Poster" %}
    {% endif %}
  </div>
  <div class="row">
    <div class="col-sm-6">
      {% crispy show_info_form %}
    </div>
    <div class="col-sm-6">
      {% crispy date_form %}
      {% crispy event_form %}
    </div>
  </div>
{% endblock %}
{% block extraSubmit %}{% progress_bar %}{% endblock %}


{% block script %}
  {{ block.super }}
  {% progress_bar_media %}
  <script type="text/javascript">
    {% comment %}Date picker{% endcomment %}
    $(function () {
        $('#id_start_0').datetimepicker({pickTime: false});
        $('#id_start_1').datetimepicker({pickDate: false});
        $('#id_end_0').datetimepicker({pickTime: false});
        $('#id_end_1').datetimepicker({pickDate: false});
        $('#id_end_recurring_period').datetimepicker({pickTime: false});
    });
    {% comment %}End recurrence data{% endcomment %}
    $("#id_recurrence").on('change', function(){
      var inputValue = this.value;
      if(inputValue=="ONCE"){
        $("#div_id_end_recurring_period").hide();
      }
      else{
        $("#div_id_end_recurring_period").show();
      }
    }).change();
    {% comment %}End recurrence data{% endcomment %}
    function show_image_form() {
      $('#add-poster').hide();
      $('#poster-form').show();
    }
    $(document).ready(function() {
      $('#poster-form').hide();
      $('#poster-form').before(function() {
        return $("<p id='add-poster'><button type='button' class='btn btn-link'><span class='text-muted fa fa-picture-o fa-3x'></span> Attach Photo</button></p>").click(show_image_form);
      })
    });
  </script>
  {% comment %}Image picker{% endcomment %}
  {% include "utils/_image_script.html" with selectorID='#id_poster' uploadDiv='#div_id_image' selectDiv='#div_id_poster' page=request.GET.page images=images %}
{% endblock %}