composersCouch/urls.py
import autocomplete_light
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('composersCouch.views',
    url(r'^$',
        'home',
        name='home'),
    url(r'^team/$',
        'load_template',
        {'template_name': 'footer/team.html'},
        name='team'),
    url(r'^credit/$',
        'load_template',
        {'template_name': 'footer/credit.html'},
        name='credit'),
    url(r'^colorScheme/$',
        'load_template',
        {'template_name': 'footer/colors.html'},
        name='colors'),
)

urlpatterns += patterns('',
    url(r'^f/(?P<username>[-\w]+)/',
        include('customProfile.fan.urls', namespace='fan')),
    url(r'^m/(?P<username>[-\w]+)/',
        include('customProfile.musician.urls', namespace='musician')),
    url(r'^v/(?P<username>[-\w]+)/',
        include('customProfile.venue.urls', namespace='venue')),
)

urlpatterns += patterns('',
    url(r'', include('accounts.urls')),
    url(r'', include('customProfile.urls')),
    url(r'', include('feeds.urls')),
    url(r'', include('schedule.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^gallery/', include('photos.urls', namespace='photos')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # WARNING/TODO: media url is hard coded in auto complete templates
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':  getattr(settings, 'MEDIA_ROOT', '/media')}),
    url(r'^messages/', include('messages.urls')),
    url(r'^progressbarupload/', include('progressbarupload.urls')),
    url(r'^request/', include('request.urls')),
    url(r'^search', include('search.urls')),
)

customProfile/fan/urls.py
from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # News Tab
    url(r'^$',
        'profileRedirect',
        {'redirect_url': 'fan:news'},
        name='home'),
    url(r'^news/$',
        'fan_news',
        name='news'),
    # Photos
    url(r'^photos/', include(patterns(view_location,
        url(r'^$',
            'fan_photos',
            name='photos'),
    ))),
)
"""
view_location = 'customProfile.fan.views'
urlpatterns += patterns(view_location,

)
"""

customProfile/musician/urls.py
from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # News Tab
    url(r'^$',
        'profileRedirect',
        {'redirect_url': 'musician:news'},
        name='home'),
    url(r'^news/$',
        'artist_news',
        name='news'),
    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^links/edit/$',
            'artist_social_links',
            name='socialLinksForm'),
    ))),
    # Shows Tab
    url(r'^shows/', include(patterns(view_location,
        url(r'^$',
            'shows',
            name='shows'),
        url(r'^(?P<year>\d{4})/$',
            'shows',
            name='shows'),
    ))),
    # Photos
    url(r'^photos/', include(patterns(view_location,
        url(r'^$',
            'artist_photos',
            name='photos'),
        url(r'^links/edit/$',
            'artist_photo_links',
            name='photoLinksForm'),
    ))),
    # Music Tab
    url(r'^music/', include(patterns(view_location,
        url(r'^links/edit/$',
            'music_links',
            name='musicLinksForm'),
    ))),
    # Video Tab
    url(r'^videos/', include(patterns(view_location,
        url(r'^links/edit/$',
            'artist_video_links',
            name='videoLinksForm'),
    ))),
)

view_location = 'customProfile.musician.views'
urlpatterns += patterns(view_location,
    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^$',
            'about',
            name='about'),
        # Forms
        url(r'^biography/edit/$',
            'biography',
            name='biographyForm'),
        url(r'^contact/edit/$',
            'contact_info',
            name='userContactForm'),
        url(r'^member/add/$',
            'members',
            name='memberForm'),
        url(r'^member/edit/(?P<memberID>[\.\w-]+)$',
            'members',
            name='memberForm'),
        url(r'^(?P<contactType>[\.\w-]+)/edit/$',
            'contacts',
            name='contactForm'),
    ))),

    # Music Tab
    url(r'^music/', include(patterns(view_location,
        url(r'^$',
            'music',
            name='music'),
        # Forms
        url(r'^album/add/$',
            'AddEditAlbum',
            name='albumForm'),
        url(r'^album/(?P<albumID>[\.\w-]+)/edit/$',
            'AddEditAlbum',
            name='editAlbumForm'),
        url(r'^album/(?P<albumID>[\.\w-]+)/tracks/add/$',
            'AddEditTracks',
            name='tracksForm'),
        #url(r'^interview/add/$',
        #    'interview_form',
        #    name='interview_form'),
        #url(r'^interview/add/(?P<trackID>[\.\w-]+)$',
        #    'interview_form',
        #    name='interview_form'),
    ))),
    # Video Tab
    url(r'^videos/', include(patterns(view_location,
        url(r'^$',
            'videos',
            name='videos'),
        # Forms
        url(r'^album/add/$',
            'AddEditAlbum',
            {'success_url': 'musician:video_tracks_form'},
            name='video_album_form'),
        url(r'^album/(?P<albumID>[\.\w-]+)/edit/$',
            'AddEditAlbum',
            {'success_url': 'musician:video_tracks_form'},
            name='video_edit_album'),
        url(r'^album/(?P<albumID>[\.\w-]+)/tracks/add/$',
            'add_video_to_album',
            name='video_tracks_form'),
        #url(r'^interview-video/add/$',
        #    'interview_video_form',
        #    name='interview_video_form'),
        #url(r'^interview-video/add/(?P<trackID>[\.\w-]+)$',
        #    'interview_video_form',
        #    name='interview_video_form'),
    ))),

)

customProfile/venue/urls.py
from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # News Tab
    url(r'^$',
        'profileRedirect',
        {'redirect_url': 'venue:news'},
        name='home'),
    url(r'^news/$',
        'venue_news',
        name='news'),
    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^links/edit/$',
            'venue_social_links',
            name='socialLinksForm'),
    ))),
    # Shows Tab
    url(r'^shows/', include(patterns(view_location,
        url(r'^$',
            'venue_shows',
            name='shows'),
        url(r'^(?P<year>\d{4})/$',
            'venue_shows',
            name='shows'),
    ))),
    # Photos Tab
    url(r'^photos/', include(patterns(view_location,
        url(r'^$',
            'venue_photos',
            name='photos'),
        url(r'^links/edit/$',
            'venue_photo_links',
            name='photoLinksForm'),
    ))),
)

view_location = 'customProfile.venue.views'
urlpatterns += patterns(view_location,

    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^$',
            'venue_about',
            name='about'),
        # Forms
        url(r'^biography/edit/$',
            'biography',
            name='biographyForm'),
        url(r'^contact/edit/$',
            'contact_info',
            name='contactForm'),
        url(r'^equipment/edit/(?P<category>[\.\w-]+)/$',
            'equipment',
            name='equipmentForm'),
        url(r'^hours/edit/$',
            'hours',
            name='hoursForm'),
        url(r'^policies/edit/$',
            'policies',
            name='policiesForm'),
        url(r'^seating/edit/$',
            'seating',
            name='seatingForm'),
        url(r'^staff/edit/$',
            'staff',
            name='staffForm'),
        url(r'^staff/edit/(?P<staffID>[\.\w-]+)/$',
            'staff',
            name='staffForm'),
    ))),

)

feeds/urls.py
from django.conf.urls import include, patterns, url


view_location = 'feeds.views'

# used in feed system for redirect when appending zipcode onto url
homeCategory = 'shows'
homeScope = 'global'

urlpatterns = patterns(view_location,
    url(r'^follow/$',
        'follow', name='follow'),
    url(r'^remove_post/$',
        'remove_post', name='remove_post'),
    url(r'^upvote/$',
        'up_vote', name='upvote'),
    url(r'^zipcode/$',
        'zipcode', name='zipcode'),
    url(r'^filter/$',
        'filter', name='filter'),
    url(r'^genre/$',
        'genre', name='genre'),
    url(r'^availability/$',
        'availability', name='availability'),

    url(r'^(?P<order>[-\w]+)/', include(patterns(view_location,
        url(r'^artists/(?P<scope>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'^artists/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'artist/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_artists',
                name='available_artists'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_artists',
                name='available_artists'),
        ))),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^shows/(?P<scope>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^shows/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^venues/(?P<scope>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'^venues/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'venue/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_venues',
                name='available_venues'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_venues',
                name='available_venues'),
        ))),
    ))),
    url(r'^updates/', include(patterns(view_location,
        url(r'^(?P<scope>[-\w]+)/$',
            'updates',
            name='updates'),
        url(r'^(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'updates',
            name='updates'),
    ))),
)

messages/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic.base import RedirectView


urlpatterns = patterns('messages.views',
    url(r'^$', RedirectView.as_view(url='inbox/')),
    url(r'^inbox/$', 'inbox', name='messages_inbox'),
    url(r'^sent/$', 'sent', name='messages_sent'),
    url(r'^compose/$', 'compose', name='messages_compose'),
    url(r'^compose/(?P<recipient>[\+\w]+)/$', 'compose', name='messages_compose'),
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='messages_detail'),
    url(r'^delete/(?P<thread_id>[\d]+)/$', 'delete', name='messages_delete'),
    url(r'^restore/(?P<thread_id>[\d]+)/$', 'restore', name='messages_restore'),
    url(r'^batch-update/$', 'batch_update', name='messages_batch_update'),
    url(r'^trash/$', 'trash', name='messages_trash'),

    url(r'^message-reply/(?P<thread_id>[\d]+)/$', 'message_ajax_reply', name="message_reply"),

)

photos/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from views import (ImageListView, UpdateImage, CreateImage, DeleteImage,
                   ImageView)


urlpatterns = patterns('photos.views',
     url(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

     url(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

     url(r'^upload/$', CreateImage.as_view(), name='upload'),

     url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
     url(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
     url(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
     url(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
     url(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),
)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'accounts/password_reset_form.html',
                    'email_template_name': 'accounts/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'accounts/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'accounts/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'accounts/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    #url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
    #   userena_views.direct_to_user_template,
    #   {'template_name': 'userena/signup_complete.html',
    #    'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
    #                      'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
    #   name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

photos/models/image.py
from bases.image import BaseImage
from django.utils.translation import ugettext_lazy as _
from photos.utils import load_class, get_model_string

class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        app_label = 'photos'

composersCouch/templates/profile/musician/about.html
{% extends 'profile/musician/detail.html' %}
{% load i18n %}
{% load url from future %}

{% block aboutClass %}active{% endblock %}
{% block dropdownTitle %}About{% endblock %}

{% block panelBody %}
<div class='about'>
  <div class="row">
    <div class="col-xs-12">
      <div class="pull-right"><p>
        {% with social=profile.social_links %}
            {% if social.facebook %}<a href="{{ social.facebook }}" target="_blank" class="btn btn-facebook"><span class="fa fa-facebook"></span></a>{% endif %}
            {% if social.twitter %}<a href="{{ social.twitter }}" target="_blank" class="btn btn-twitter"><span class="fa fa-twitter"></span></a>{% endif %}
            {% if social.google_plus %}<a href="{{ social.google_plus }}" target="_blank" class="btn btn-google"><span class="fa fa-google-plus"></span></a>{% endif %}
        {% endwith %}
        <a href="{% url 'musician:socialLinksForm' username  %}" class="{{isEditable}}">Edit<span class="hidden-xs"> Links</span></a>
      </p></div>
    </div>
  </div>
  <div class="biography">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Biography</h3>
      </div>
      <div class="panel-body">
        <p>{{ musicianProfile.biography }}</p>
        <a class="{{isEditable}} editMusicianBiography" href="{% url 'musician:biographyForm' username  %}">
          Edit
        </a>
      </div>
    </div>
  </div>
  <div class="panel panel-default members">
    <div class="panel-heading">
      <h3>Members</h3>
    </div>
    <div class="panel-body">
    {% for member in members %}
      <div class='member '>
        <h4>{{ member.name }}</h4>
        <p>
          {% for instrument in member.instruments.all %}
            {{ instrument }}
            {% if not forloop.last %},{% endif %}
          {% endfor %}
        </p>
        <p>{{ member.biography }}</p>
      </div>
    {% endfor %}
    <a class="{{isEditable}} editMusicianMembers" href="{% url 'musician:memberForm' username %}">
      Edit
    </a>
    </div>
  </div>
  <div class='contact'>
    <div class="row no-gutter">
      <div class="col-sm-5ths left">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="row no-gutter">
              <div class="col-md-6 left">
                <h4 class="pull-left">Band</h4>
              </div>
              <div class="col-md-6 right">
                <a href="{% url 'messages_compose' username %}" class="pull-right btn btn-default">{% trans "Contact" %}</a>
              </div>
            </div>
          </div>
          <div class="panel-body">
            {% include "profile/_contact.html" with contact_info=profile.contact_info %}
            <a class="editMusicianContact {{isEditable}}" href="{% url 'musician:userContactForm' username %}">Edit</a>
          </div>
        </div>
      </div>
      <div class="col-sm-5ths center">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Booking</h4>
          </div>
          <div class="panel-body">
            {% include "profile/_contact.html" with contact_info=musicianProfile.booking_contact %}
            <a class="editMusicianContact {{isEditable}}" href="{% url 'musician:contactForm' username 'booking' %}">Edit</a>
          </div>
        </div>
      </div>
      <div class="col-sm-5ths center">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Label</h4>
          </div>
          <div class="panel-body">
            {% include "profile/_contact.html" with contact_info=musicianProfile.label_contact %}
            <a class="editMusicianContact {{isEditable}}" href="{% url 'musician:contactForm' username 'label' %}">Edit</a>
          </div>
        </div>
      </div>
      <div class="col-sm-5ths center">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Management</h4>
          </div>
          <div class="panel-body">
            {% include "profile/_contact.html" with contact_info=musicianProfile.management_contact %}
            <a class="editMusicianContact {{isEditable}}" href="{% url 'musician:contactForm' username 'management' %}">Edit</a>
          </div>
        </div>
      </div>
      <div class="col-sm-5ths right">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4>Press</h4>
          </div>
          <div class="panel-body">
            {% include "profile/_contact.html" with contact_info=musicianProfile.press_contact %}
            <a class="editMusicianContact {{isEditable}}" href="{% url 'musician:contactForm' username 'press' %}">Edit</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="modal" id=""  tabindex="-1" role="dialog" aria-hidden="true"></div>

{% endblock %}

composersCouch/templates/profile/musician/detail.html
{% extends 'profile/detail.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{{ musicianProfile.name}}{% endblock %}
{% block content_title %}<h2>{{ musicianProfile.name }}</h2>{% endblock %}

{% block name %}{{ musicianProfile.name }}{% endblock %}

{% block tabs %}
  {% block dropdownTabs %}
    <li class="left {% block aboutClass %}{% endblock %}">
      <a href="{% url 'musician:about' username  %}">About</a>
    </li>
    <li class="{% block newsClass %}{% endblock %}">
      <a href="{% url 'musician:news' username  %}">News</a>
    </li>
    <li class="{% block showsClass %}{% endblock %}">
      <a href="{% url 'musician:shows' username  %}">Shows</a>
    </li>
    <li class="{% block musicClass %}{% endblock %}">
      <a href="{% url 'musician:music' username  %}">Music</a>
    </li>
    <li class="{% block photosClass %}{% endblock %}">
      <a href="{% url 'musician:photos' username  %}">Photos</a>
    </li>
    <li class="{% block videosClass %}{% endblock %}">
      <a href="{% url 'musician:videos' username  %}">Videos</a>
    </li>
  {% endblock %}
{% endblock %}

composersCouch/templates/profile/musician/news.html
{% extends 'profile/musician/detail.html' %}
{% load crispy_forms_tags i18n progress_bar %}
{% crispy PostForm PostForm.helper %}

{% block newsClass %}active{% endblock %}
{% block dropdownTitle %}News{% endblock %}

{% block panelBody %}
  {% if user.is_authenticated %}
    {% include "profile/_news.html" with post_form=post_form photo_form=photo_form %}
  {% endif %}
  {% for activity in activities %}
    {% include "feeds/_post.html" with post=activity.post %}
  {% empty %}
    <p>No news to display.</p>
  {% endfor %}
{% endblock %}

{% block script %}
  {{ block.super }}
  {% progress_bar_media %}
  {% include "utils/_image_script.html" with selectorID='#id_photo' uploadDiv='#div_id_image' selectDiv='#div_id_photo' page=request.GET.page images=images %}
  <script type="text/javascript">
    $(document).ready(function() {
      $("#post-form").hide();
      $("#attach-photo-form").hide();
      $("#show-post-form").click(function() {
        $("#post-form").show();
        $("#show-post-form").hide();
      });
      $("#attach-photo").click(function() {
        $("#attach-photo-form").toggle();
      });
    });
  </script>
{% endblock %}

composersCouch/templates/profile/musician/photos.html
{% extends 'profile/musician/detail.html' %}
{% load i18n %}
{% load url from future %}

{% block photosClass %}active{% endblock %}
{% block dropdownTitle %}Photos{% endblock %}

{% block panelBody %}
  <div class="row">
    <div class="col-xs-12">
      <a class="{{isEditable}} btn btn-success" href="{% url 'photos:upload' %}">
        <span class="fa fa-arrow-up"></span> Add Photo
      </a>
      <div class="pull-right"><p>
        {% with social=profile.social_links %}
          {% if social.instagram %}<a href="{{ social.instagram }}" target="_blank" class="btn btn-instagram"><span class="fa fa-instagram"></span></a>{% endif %}
          {% if social.tumblr %}<a href="{{ social.tumblr }}" target="_blank" class="btn btn-tumblr"><span class="fa fa-tumblr"></span></a>{% endif %}
        {% endwith %}
        <a href="{% url 'musician:photoLinksForm' username  %}" class="{{isEditable}}">Edit<span class="hidden-xs"> Links</span></a>
      </p></div>
    </div>
  </div>
  <div class="{% if not images %}{{isEditable}}{% endif %}">
    {% include "profile/photos.html" with images=images %}
  </div>

{% endblock %}

composersCouch/templates/profile/musician/shows.html
{% extends 'profile/musician/detail.html' %}
{% load i18n %}
{% load url from future %}

{% block showsClass %}active{% endblock %}
{% block dropdownTitle %}Shows{% endblock %}

{% block panelBody %}
  {% include "profile/_shows.html" with currentYear=currentYear year=year request=request slug=musicianProfile.profile.user.calendar.slug name=musicianProfile events=events  %}
{% endblock %}