composersCouch/urls.py
import autocomplete_light
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('composersCouch.views',
    url(r'^$',
        'home',
        name='home'),
    url(r'^team/$',
        'load_template',
        {'template_name': 'footer/team.html'},
        name='team'),
    url(r'^credit/$',
        'load_template',
        {'template_name': 'footer/credit.html'},
        name='credit'),
    url(r'^colorScheme/$',
        'load_template',
        {'template_name': 'footer/colors.html'},
        name='colors'),
)

urlpatterns += patterns('',
    url(r'^f/(?P<username>[-\w]+)/',
        include('customProfile.fan.urls', namespace='fan')),
    url(r'^m/(?P<username>[-\w]+)/',
        include('customProfile.musician.urls', namespace='musician')),
    url(r'^v/(?P<username>[-\w]+)/',
        include('customProfile.venue.urls', namespace='venue')),
)

urlpatterns += patterns('',
    url(r'', include('accounts.urls')),
    url(r'', include('customProfile.urls')),
    url(r'', include('feeds.urls')),
    url(r'', include('schedule.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^gallery/', include('photos.urls', namespace='photos')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # WARNING/TODO: media url is hard coded in auto complete templates
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':  getattr(settings, 'MEDIA_ROOT', '/media')}),
    url(r'^messages/', include('messages.urls')),
    url(r'^progressbarupload/', include('progressbarupload.urls')),
    url(r'^request/', include('request.urls')),
    url(r'^search', include('search.urls')),
)

feeds/urls.py
from django.conf.urls import include, patterns, url


view_location = 'feeds.views'

# used in feed system for redirect when appending zipcode onto url
homeCategory = 'shows'
homeScope = 'global'

urlpatterns = patterns(view_location,
    url(r'^follow/$',
        'follow', name='follow'),
    url(r'^remove_post/$',
        'remove_post', name='remove_post'),
    url(r'^upvote/$',
        'up_vote', name='upvote'),
    url(r'^zipcode/$',
        'zipcode', name='zipcode'),
    url(r'^filter/$',
        'filter', name='filter'),
    url(r'^genre/$',
        'genre', name='genre'),
    url(r'^availability/$',
        'availability', name='availability'),

    url(r'^(?P<order>[-\w]+)/', include(patterns(view_location,
        url(r'^artists/(?P<scope>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'^artists/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'artists',
            name='artists'),
        url(r'artist/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_artists',
                name='available_artists'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_artists',
                name='available_artists'),
        ))),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^requests/(?P<for>[-\w]+)/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'requests',
            name='requests'),
        url(r'^shows/(?P<scope>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^shows/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'shows',
            name='shows'),
        url(r'^venues/(?P<scope>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'^venues/(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'venues',
            name='venues'),
        url(r'venue/availability/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/', include(patterns(view_location,
            url(r'^$',
                'available_venues',
                name='available_venues'),
            url(r'^(?P<zipcode>[-\w]+)/$',
                'available_venues',
                name='available_venues'),
        ))),
    ))),
    url(r'^updates/', include(patterns(view_location,
        url(r'^(?P<scope>[-\w]+)/$',
            'updates',
            name='updates'),
        url(r'^(?P<scope>[-\w]+)/(?P<zipcode>[-\w]+)/$',
            'updates',
            name='updates'),
    ))),
)

messages/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic.base import RedirectView


urlpatterns = patterns('messages.views',
    url(r'^$', RedirectView.as_view(url='inbox/')),
    url(r'^inbox/$', 'inbox', name='messages_inbox'),
    url(r'^sent/$', 'sent', name='messages_sent'),
    url(r'^compose/$', 'compose', name='messages_compose'),
    url(r'^compose/(?P<recipient>[\+\w]+)/$', 'compose', name='messages_compose'),
    url(r'^view/(?P<thread_id>[\d]+)/$', 'view', name='messages_detail'),
    url(r'^delete/(?P<thread_id>[\d]+)/$', 'delete', name='messages_delete'),
    url(r'^restore/(?P<thread_id>[\d]+)/$', 'restore', name='messages_restore'),
    url(r'^batch-update/$', 'batch_update', name='messages_batch_update'),
    url(r'^trash/$', 'trash', name='messages_trash'),

    url(r'^message-reply/(?P<thread_id>[\d]+)/$', 'message_ajax_reply', name="message_reply"),

)

photos/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from views import (ImageListView, UpdateImage, CreateImage, DeleteImage,
                   ImageView)


urlpatterns = patterns('photos.views',
     url(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

     url(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

     url(r'^upload/$', CreateImage.as_view(), name='upload'),

     url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
     url(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
     url(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
     url(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
     url(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),
)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'accounts/password_reset_form.html',
                    'email_template_name': 'accounts/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'accounts/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'accounts/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'accounts/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    #url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
    #   userena_views.direct_to_user_template,
    #   {'template_name': 'userena/signup_complete.html',
    #    'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
    #                      'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
    #   name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

photos/models/image.py
from bases.image import BaseImage
from django.utils.translation import ugettext_lazy as _
from photos.utils import load_class, get_model_string

class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        app_label = 'photos'

composersCouch/views.py
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic import FormView
from django.views.generic.base import TemplateView

from accounts.models import FanProfile, MusicianProfile, VenueProfile
from feeds.views import requests, shows


def load_template(request, template_name, extra_context=None):
    if not extra_context: extra_context = dict()
    return render(request, template_name, extra_context)

def search(request, template_name='search/search.html', ajax_template='autocomplete/search.html'):
    if request.is_ajax():
        template_name = ajax_template

    q = request.GET.get('q', '')
    context = {'q': q}
    queries = {}
    queries['musicians'] = MusicianProfile.objects.filter(name__icontains=q)[:3]
    queries['venues'] = VenueProfile.objects.filter(name__icontains=q)[:3]

    context.update(queries)
    return render(request, template_name, context)

class HomeView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            if self.request.user.profile.profile_type == 'm':
                return requests(self.request, scope='local', kwargs={'for':'band','scope':'local'})
            elif self.request.user.profile.profile_type == 'v':
                return requests(self.request, scope='local', kwargs={'for':'venue','scope':'local'})
            else:
                return shows(self.request, scope='local')
        return super(HomeView, self).dispatch(*args, **kwargs)

home = HomeView.as_view()

# Mixin to handle multiple form classses
class MultipleFormsView(FormView):
    form_classes = {}
    template_name = None
    success_url = 'home'

    def are_forms_valid(self, forms):
        for key, form in forms.iteritems():
            if not form.is_valid():
                return False
        return True

    def forms_valid(self, forms):
        return get_success_url(self, **kwargs)

    def forms_invalid(self, forms):
        context = self.get_context_data()
        context['next'] = self.request.POST.get('next')
        context.update(forms)
        return render(self.request, self.template_name, context)

    def get(self, request, username=None, **kwargs):
        context = self.get_context_data()
        context.update(self.get_forms())
        # TODO: append next url to response?
        return render_to_response(self.template_name,
                                  context_instance=RequestContext(request, context))

    def get_context_data(self, **kwargs):
        context = super(MultipleFormsView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context

    def get_forms(self):
        forms = {}
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(initial=initial[key], **form_kwargs)
        return forms

    def get_form_kwargs(self):
        kwargs = {}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_initial_data(self):
        initial = {}
        for key, form_class in self.form_classes.iteritems():
            initial[key] = {}
        return initial

    def get_success_url(self, **kwargs):
        if self.request.POST.has_key('next'):
            return HttpResponseRedirect(self.request.POST['next'])
        else:
            return redirect(self.success_url, **kwargs)

    def post(self, request, **kwargs):
        forms = self.get_forms()
        if self.are_forms_valid(forms):
            return self.forms_valid(forms)
        else:
            return self.forms_invalid(forms)

class MultipleModelFormsView(MultipleFormsView):
    """ The object coresponding to the form must use the sam key """

    def get_objects(self):
        objects = {}
        for key, form_class in self.form_classes.iteritems():
            objects[key] = None
        return objects

    def get_forms(self):
        forms = {}
        objects = self.get_objects()
        initial = self.get_initial_data()
        form_kwargs = self.get_form_kwargs()
        for key, form_class in self.form_classes.iteritems():
            forms[key] = form_class(instance=objects[key], initial=initial[key], **form_kwargs)
        return forms


def reset():
     cursor = connection.cursor()
     cursor.execute("SELECT setval('location_id_key', (SELECT MAX(id) FROM contact_location)+1)")
     print "success"

composersCouch/templates/photos/base.html
{% extends base.html %}
{% load i18n %}
{% load url from future %}

{% block head %}
    {% if PHOTOS_LOAD_CSS %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}photos.css" media="screen" />
    {% endif %}
{% endblock %}

{% block breadcrumb %}
    <ul class='breadcrumb'>
        {% if request.path != '/' %}
            <li><a href="/">{% trans "Home" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% if request.path != photos_index_url %}
            <li><a href="{{ photos_index_url }}">{% trans "Gallery" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% block photos-breadcrumb %}
    {% endblock %}
    </ul>
{% endblock %}

{% block content %}
{% endblock content %}

{% block content-related %}
        {% block photos-info %}
        {% endblock %}
        <div id="controls">
            <ul>
                {% if photos_perms.add_image or request.user.is_superuser %}
                    <li><a href={% url 'photos:upload' %}>{% trans "Upload image" %}</a></li>
                {% endif %}
                {% if photos_perms.add_album or request.user.is_superuser %}
                    <li><a href={% url 'photos:create-album' %}>{% trans "Create new album" %}</a></li>
                {% endif %}
                {% block controls %}
                {% endblock controls %}
            </ul>
        </div>
        {% block photos-related %}
        {% endblock %}
{% endblock %}

composersCouch/templates/photos/image-href.html
{% load url from future %}
{% if album %}
    {% url 'photos:image-album' album_id=album.id pk=image.id %}
{% else %}
    {% if tag %}
        {% url 'photos:image-tag' tag=tag pk=image.id %}
    {% else %}
        {{ image.get_absolute_url }}
    {% endif %}
{% endif %}

composersCouch/templates/photos/image-list.html
{% load i18n %}
{% load thumbnail %}

<div id="image-thumbnails">
    {% for image in image_list %}
        {% thumbnail image.image "120x120" crop="center" as im %}
            <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
            </a>
            <a href="{% url '{{ image.get_absolute_url }}' %}">
                {% if image.title %}
                    <br><span class='image-title'>{{ image.title }}</span>
                {% else %}
                    {% trans 'Info' %}
                {% endif %}
            </a>
        {% endthumbnail %}
    {% endfor %}
    {% include "photos/pagination.html" %}
</div>

composersCouch/templates/photos/image-scope.html
{% load i18n %}
{% if view_user %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-view-user'>{% endif %}
        {% trans "User" %}: {{ view_user }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if album %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
        {% trans "Album" %}: {{ album.name }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if tag %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
    {% trans "Tag" %}: {{ tag }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}

composersCouch/templates/photos/image.html
{% extends "base.html" %}
{% load i18n thumbnail %}

{% block title %}
    {% trans "Photo" %} - {{ image.title }}
{% endblock %}

{% block header %}
  {% if image.title %}
    <h3>{{ image.title }}</h3>
  {% endif %}
  {% if image.title %}
    <div class="image-description">
      <p>{{ image.description }}</p>
    </div>
  {% endif %}
{% endblock %}
{% block content %}
  <div id="image-view">
    {% thumbnail image.image "x500" upscale=false as im %}
      <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
    {% endthumbnail %}
  </div>
  {% if request.user == image.user or perms.photos.moderate_images %}
    <a href="{% url 'photos:update-image' image.id %}">{% include "_editLink.html" with text="Edit Photo" %}</a>
    {% comment %}
    TODO: fix issuewith bad requests
    <a class="pull-right" href="{% url 'photos:delete-image' image.id %}">{% include "_deleteLink.html" with text="Delete Photo" %}</a>
    {% endcomment %}
  {% endif %}
{% endblock %}

composersCouch/templates/photos/image_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

composersCouch/templates/photos/image_delete.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
  <h4>{% trans "Are you sure that you would like to delete this image?" %}</h4>
  <form method="post" action="{% url 'photos:delete-image' image.id %}">
    {% csrf_token %}
    <a class='btn btn-primary' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
    <input type="submit" class='btn btn-danger' value="{% trans 'Yes, I am sure' %}" />
  </form>
{% endblock %}

composersCouch/templates/photos/image_list.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load url from future %}

{% block photos-breadcrumb %}
    {% with "li" as scope_tag %}
        {% include "photos/image-scope.html" %}
    {% endwith %}
{% endblock %}

{% block title %}
    {% include "photos/image-scope.html" %}
{% endblock %}

{% block photos-info %}
    {% if view_user and PHOTOS_SHOW_USER %}
        {% with user=view_user %}
            {% include "photos/user_info.html" %}
        {% endwith %}
    {% endif %}
    {% if album and PHOTOS_SHOW_USER %}
        {% with user=album.user %}
            {% include "photos/user_info.html" %}
        {% endwith %}
    {% endif %}

{% endblock %}


{% block controls %}
    {% if album %}
        {% if request.user == album.user or perms.photos.moderate_albums %}
            <li><a href='{% url 'photos:update-album' pk=album.pk %}'>{% trans "Edit album" %}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% include "photos/image-scope.html" %}
    </h1>
    {% include "photos/pagination.html" %}
    <div id="image-thumbnails">
        {% for image in image_list %}
            <div class='image-preview'>
            {% thumbnail image.image "120x120" crop="center" as im %}
                <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                    <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
                </a>
                <a href="{% include "photos/image-href.html" %}">
                    {% if image.title %}
                        <br><span class='image-title'>{{ image.title }}</span>
                    {% else %}
                        {% trans 'Info' %}
                    {% endif %}
                </a>
            {% endthumbnail %}
            </div>
        {% endfor %}
    </div>
    {% include "photos/pagination.html" %}
{% endblock %}

composersCouch/templates/photos/pagination.html
{% load i18n %}

{% if is_paginated %}
    <div class="pagination">
        <ul>

            <li class="prev {% if not page_obj.has_previous %}disabled{% endif %}">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" >← {% trans "previous page" %}</a>
            </li>
            {% for page in page_obj.pages %}
                {% if page %}
                    <li {% ifequal page page_obj.number %}class="disabled"{% endifequal %}>
                        <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="disabled">
                        ...
                    </li>
                {% endif %}
            {% endfor %}
            <li class="next {% if not page_obj.has_next %}disabled{% endif %}">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" >{% trans "next page" %} →</a>
            </li>
        </ul>
    </div>
{% endif %}

composersCouch/templates/photos/pphoto.html
<link rel="stylesheet" href="{{ STATIC_URL }}prettyphoto/css/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />
<script src="{{ STATIC_URL }}prettyphoto/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" charset="utf-8">
    var prettyparams = {
        animation_speed: 'fast',
        slideshow: 3000,
        autoplay_slideshow: false,
        opacity: 0.7,
        show_title: true,
        allow_resize: true,
        default_width: 1000,
        default_height: 344,
        counter_separator_label: '/',
        theme: 'facebook',
        overlay_gallery: true,
        changepicturecallback: function() {$pp_overlay.css({'height':$(document).height()})},
        };
    $(function(){$("a[rel^='gallery-image']").prettyPhoto(prettyparams)});
</script>

composersCouch/templates/photos/tag-cloud.html
{% load tagging_tags %}
{% load i18n %}
{% load url from future %}

{% if PHOTOS_SHOW_TAGS %}
    <div id="tag-cloud">
        <h1>{% trans "Tags" %}</h1>
        {% tag_cloud_for_model photos.Image as image_tags %}
        {% for tag in image_tags %}
            <a href={% url 'photos:tag' tag.name %}>{{ tag.name }}</a>
        {% endfor %}
    </div>
{% endif %}

composersCouch/templates/photos/tag.html
{% extends "base.html" %}

{% load i18n %}
{% load thumbnail %}

{% block title %}
    {% trans "Gallery" %} - {% trans "Tag" %}: {{ tag }}
{% endblock %}

{% block photos-breadcrumb %}
    <li>{% trans "Tag" %}: {{ tag }}</li>
{% endblock %}

{% block content %}
    <h1>{% trans "Tag" %} - {{ tag }}</h1>
    {% include "photos/image-list.html" %}
{% endblock content %}

{% block content-related %}
    {% include "photos/tag-cloud.html" %}
{% endblock %}

composersCouch/templates/photos/user_info.html
{% load i18n %}
{% load thumbnail %}

{# if we can't get profile then return user model itself #}
{% with profile=user.get_profile|default_if_none:user %}
    <div class="user-info">
        <h2>{% trans "User" %}</h2>
        <div class="avatar">
            <a href="{{ profile.get_absolute_url }}">
                {% thumbnail profile.avatar "80x80" as avatar %}
                    <img src="{{ avatar.url }}" alt="avatar">
                {% empty %}
                {% endthumbnail %}
            </a>
        </div>
        <div class="user-name">
            <a href="{{ profile.get_absolute_url }}">
                {{ user }}
            </a>
        </div>
     </div>
{% endwith %}